import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";
import fs from "fs";
import { Firestore } from "@google-cloud/firestore";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Gemini Client Lazily to prevent crash on startup if key is missing
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey === "MY_GEMINI_API_KEY") {
    throw new Error("GEMINI_API_KEY environment variable is not configured. Please add it to your project secrets.");
  }
  if (!aiClient) {
    aiClient = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClient;
}

// Ensure clean error response helper
function sendError(res: express.Response, error: any) {
  console.error("AI Error:", error);
  res.status(500).json({ 
    error: error instanceof Error ? error.message : "An unexpected server-side error occurred." 
  });
}

// 1. Suggest Chores API
app.post("/api/suggest-chores", async (req, res) => {
  try {
    const age = req.body.age || 8;
    const ai = getGeminiClient();
    
    const prompt = `Suggest 5 age-appropriate chores for a ${age} year old child. For each chore provide: name, brief description, and suggested points value between 10 and 100. Return as JSON array with fields: name, description, points`;
    
    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              name: {
                type: Type.STRING,
                description: "The title of the chore; keep it short and action-oriented."
              },
              description: {
                type: Type.STRING,
                description: "A very brief, simple description of what needs to be done."
              },
              points: {
                type: Type.INTEGER,
                description: "Points reward value between 10 and 100 based on standard difficulty."
              }
            },
            required: ["name", "description", "points"]
          }
        }
      }
    });

    const text = response.text;
    if (!text) {
      return res.status(500).json({ error: "No response text generated by AI." });
    }
    const data = JSON.parse(text);
    res.json(data);
  } catch (error) {
    sendError(res, error);
  }
});

// 2. Suggest Rewards API
app.post("/api/suggest-rewards", async (req, res) => {
  try {
    const age = req.body.age || 8;
    const ai = getGeminiClient();

    const prompt = `Suggest 5 creative and motivating rewards for a child aged ${age}. Make them fun, wholesome, non-monetary or low-cost, and exciting. Return as JSON array with fields: name, description, suggestedPoints`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              name: {
                type: Type.STRING,
                description: "The name of the reward (e.g., Extra Screen Time)."
              },
              description: {
                type: Type.STRING,
                description: "Short details explaining what the child gets."
              },
              suggestedPoints: {
                type: Type.INTEGER,
                description: "Points cost associated with the reward, normally 25 to 200 points."
              }
            },
            required: ["name", "description", "suggestedPoints"]
          }
        }
      }
    });

    const text = response.text;
    if (!text) {
      return res.status(500).json({ error: "No response text generated by AI." });
    }
    const data = JSON.parse(text);
    res.json(data);
  } catch (error) {
    sendError(res, error);
  }
});

// 3. Motivational Message on Redemption
app.post("/api/motivate", async (req, res) => {
  try {
    const { name, reward } = req.body;
    if (!name || !reward) {
      return res.status(400).json({ error: "Name and reward are required fields." });
    }
    const ai = getGeminiClient();

    const prompt = `Write a short, fun, encouraging message (2-3 sentences) for a child named ${name} who just redeemed a reward called "${reward}". Make it highly celebratory, energetic, and age-appropriate with relevant emojis.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            message: {
              type: Type.STRING,
              description: "The celebratory motivational text message."
            }
          },
          required: ["message"]
        }
      }
    });

    const text = response.text;
    if (!text) {
      return res.status(500).json({ error: "No response text generated by AI." });
    }
    const data = JSON.parse(text);
    res.json(data);
  } catch (error) {
    sendError(res, error);
  }
});

const DATA_FILE = path.join(process.cwd(), "family-data.json");

// Lazy load Firestore client to keep startup safe and fast
let dbClient: Firestore | null = null;
function getFirestoreDb(): Firestore {
  if (!dbClient) {
    dbClient = new Firestore({
      projectId: "gen-lang-client-0834237355",
      databaseId: "ai-studio-chorequest-ee1e3543-2f2a-4e12-a4fd-52aacae6d3d9"
    });
  }
  return dbClient;
}

// 4. Family Data - Get synchronization state fallback
app.get("/api/family-data", (req, res) => {
  try {
    if (fs.existsSync(DATA_FILE)) {
      const raw = fs.readFileSync(DATA_FILE, "utf-8");
      const parsed = JSON.parse(raw);
      return res.json({ initialized: true, ...parsed });
    }
    return res.json({ initialized: false });
  } catch (error) {
    console.error("Error reading family data from fallback file:", error);
    res.status(500).json({ error: "Failed to read family data from local backup" });
  }
});

// 5. Family Data - Update synchronization state fallback
app.post("/api/family-data", (req, res) => {
  try {
    const data = req.body;
    fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2), "utf-8");
    res.json({ success: true });
  } catch (error) {
    console.error("Error saving family data to fallback file:", error);
    res.status(500).json({ error: "Failed to save family data to local backup" });
  }
});

// Vite Middleware integration for development / production serving
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    console.log("Starting server in DEVELOPMENT mode with Vite integration...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    console.log("Starting server in PRODUCTION mode...");
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    // SPA fallback
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`ChoreQuest server is listening on http://0.0.0.0:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error("Critical: Failed to start server:", err);
});
